steps:
  - name: node:lts
    entrypoint: yarn
    args: ["install"]
  - name: node:lts
    entrypoint: yarn
    args:
      - env
      - "${_PROJECT_ID}"
      - "${_FIREBASE_WEB_API_KEY}"
      - "${_ALGOLIA_APP_ID}"
      - "${_ALGOLIA_APP_KEY}"
  - name: node:lts
    entrypoint: yarn
    args: ["build"]
    env:
      - NODE_OPTIONS=--openssl-legacy-provider
  - name: gcr.io/$PROJECT_ID/firebase
    entrypoint: yarn
    args:
      - "target"
      - "${_HOSTING_TARGET}"
      - --project
      - "${_PROJECT_ID}"
  - name: gcr.io/$PROJECT_ID/firebase
    args:
      - deploy
      - --project
      - "${_PROJECT_ID}"
      - --debug
      - --only
      - hosting
substitutions:
  _PROJECT_ID: "project-id" # default value
options:
  machineType: "N1_HIGHCPU_8"
